/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author PC Gamer
 */
public class CreateContact extends javax.swing.JFrame {
    
    private int limit=4;
    private int page=1;
    private int totalContacts = 20;
    
    /**
     * Creates new form CreateContact
     */
    public CreateContact() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        buttonFirstContact = new javax.swing.JButton();
        iconContact1 = new javax.swing.JLabel();
        textInformacionContact = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(238, 238, 238));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Contactos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        jPanel2.setBackground(new java.awt.Color(220, 220, 220));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonFirstContact.setBorderPainted(false);
        buttonFirstContact.setContentAreaFilled(false);
        buttonFirstContact.setDefaultCapable(false);
        buttonFirstContact.setFocusPainted(false);
        buttonFirstContact.setFocusable(false);
        buttonFirstContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFirstContactActionPerformed(evt);
            }
        });
        jPanel2.add(buttonFirstContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 23, 513, 68));

        iconContact1.setText(".");
        jPanel2.add(iconContact1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 36, 20, 40));

        textInformacionContact.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        textInformacionContact.setForeground(new java.awt.Color(0, 0, 0));
        textInformacionContact.setText(".");
        jPanel2.add(textInformacionContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 320, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 530, 300));

        jButton1.setIcon(new javax.swing.ImageIcon("D:\\Netbeans\\Juastapp\\JuatsappPresentacion\\src\\main\\java\\utilerias\\8666595_x_icon.png")); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonFirstContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFirstContactActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_buttonFirstContactActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    
    
    private void addContactsToPanel() {
        jPanel2.removeAll();
        int start = (page - 1) * limit;
        int end = Math.min(start + limit, totalContacts);

        for (int i = start; i < end; i++) {
            JButton contactButton = new JButton("Contact " + (i + 1));
            contactButton.setBorderPainted(false);
            contactButton.setContentAreaFilled(false);
            contactButton.setDefaultCapable(false);
            contactButton.setFocusPainted(false);
            contactButton.setFocusable(false);
            contactButton.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent evt) {
                    contactButtonActionPerformed(evt);
                }

                
            });
            jPanel2.add(contactButton);
        }
        jPanel2.revalidate();
        jPanel2.repaint();
    }
    
    private void contactButtonActionPerformed(ActionEvent evt) {
        CreateChat createChat=new CreateChat();
        createChat.show();
        this.dispose();

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateContact().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonFirstContact;
    private javax.swing.JLabel iconContact1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel textInformacionContact;
    // End of variables declaration//GEN-END:variables
}
